import {FormEvent,useEffect,useMemo,useState} from 'react'
import {api,adminSession} from '../api'
import type {AdminSummary,Order,Product,SiteConfig} from '../types'
import {BarChart3,Box,Check,ClipboardList,LogOut,Plus,RefreshCw,Save,Search,Settings2,UsersRound} from 'lucide-react'

const money=(v:string|number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB'}).format(Number(v))
const statusLabels:Record<string,string>={awaiting_payment:'Ожидает оплаты',paid:'Оплачен',in_progress:'В работе',completed:'Выполнен',cancelled:'Отменён',refunded:'Возврат'}
const statuses=Object.keys(statusLabels)

type Tab='overview'|'orders'|'products'|'settings'

export default function Admin(){
  const[authorized,setAuthorized]=useState(!!adminSession.token())
  const[token,setToken]=useState(adminSession.token())
  const[tab,setTab]=useState<Tab>('overview')
  const[summary,setSummary]=useState<AdminSummary|null>(null)
  const[orders,setOrders]=useState<Order[]>([])
  const[products,setProducts]=useState<Product[]>([])
  const[config,setConfig]=useState<SiteConfig|null>(null)
  const[error,setError]=useState('')
  const[query,setQuery]=useState('')
  const[busy,setBusy]=useState(false)
  const[adding,setAdding]=useState(false)

  async function load(){
    setError('')
    try{const[s,o,p,c]=await Promise.all([api.admin.summary(),api.admin.orders(),api.admin.products(),api.admin.siteConfig()]);setSummary(s);setOrders(o);setProducts(p);setConfig(c);setAuthorized(true)}
    catch(e:any){setError(e.message||'Не удалось открыть админку');if(String(e.message).includes('invalid_admin_token'))setAuthorized(false)}
  }
  useEffect(()=>{if(authorized)load()},[])
  async function login(e:FormEvent){e.preventDefault();adminSession.save(token);await load()}
  function logout(){adminSession.logout();setAuthorized(false);setToken('')}
  const filtered=useMemo(()=>orders.filter(o=>(o.public_id+' '+o.customer_email+' '+(o.customer_name||'')+' '+o.items.map(i=>i.title).join(' ')).toLowerCase().includes(query.toLowerCase())),[orders,query])
  async function changeStatus(id:string,status:string){await api.admin.updateOrder(id,status);await load()}
  async function toggleProduct(p:Product){await api.admin.updateProduct(p.id,{active:!p.active});await load()}
  async function updateVariant(id:number,price:string,old_price:string,delivery_type:string){await api.admin.updateVariant(id,{price:Number(price),old_price:old_price?Number(old_price):null,delivery_type});await load()}
  async function createProduct(payload:{title:string;slug:string;category:string;price:string;image_url:string;short_description:string}){const created=await api.admin.createProduct({slug:payload.slug,title:payload.title,short_description:payload.short_description,description:payload.short_description,image_url:payload.image_url,category_slug:payload.category,category_name:payload.category,active:true});await api.admin.addVariant(created.id,{name:'Стандарт',sku:`SKU-${Date.now()}`,price:Number(payload.price),old_price:null,delivery_type:config?.site_mode==='digital'?'download':config?.site_mode==='subscription'?'subscription':'service'});setAdding(false);await load()}
  async function saveConfig(e:FormEvent){e.preventDefault();if(!config)return;setBusy(true);try{const saved=await api.admin.updateSiteConfig(config);setConfig(saved);document.documentElement.style.setProperty('--primary',saved.accent_color);window.location.reload()}finally{setBusy(false)}}
  function patchConfig(key:keyof SiteConfig,value:string){setConfig(c=>c?{...c,[key]:value}:c)}
  function applyPreset(mode:'services'|'digital'|'subscription'){
    if(!config)return
    const presets={
      services:{site_mode:'services',catalog_label:'Услуги',item_label:'услуга',order_cta:'Оформить заявку',hero_cta:'Посмотреть услуги',hero_eyebrow:'ЗАДАЧА → ПОНЯТНЫЙ РЕЗУЛЬТАТ',hero_title:'Цифровые услуги без лишней бюрократии',hero_text:'Выберите готовый пакет, создайте заявку и следите за статусом в личном кабинете.'},
      digital:{site_mode:'digital',catalog_label:'Каталог',item_label:'товар',order_cta:'Купить',hero_cta:'Перейти в каталог',hero_eyebrow:'ГОТОВЫЕ ЦИФРОВЫЕ МАТЕРИАЛЫ',hero_title:'Полезные цифровые продукты в одном месте',hero_text:'Шаблоны, таблицы и материалы с понятной стоимостью и доступом через личный кабинет.'},
      subscription:{site_mode:'subscription',catalog_label:'Тарифы',item_label:'тариф',order_cta:'Подключить тариф',hero_cta:'Выбрать тариф',hero_eyebrow:'ГИБКИЕ ТАРИФЫ',hero_title:'Подписка под ваш рабочий сценарий',hero_text:'Выберите подходящий тариф, управляйте заказом и отслеживайте статус в личном кабинете.'},
    } as const
    setConfig({...config,...presets[mode]})
  }

  if(!authorized)return <div className="container page adminLogin"><form className="authCard" onSubmit={login}><span className="eyebrow">ADMIN</span><h1>Панель управления</h1><p>Введите <code>ADMIN_TOKEN</code> из backend `.env`. Токен сохраняется только в этом браузере.</p><label>Admin token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="••••••••••••"/></label>{error&&<div className="formError">{error}</div>}<button className="primary wide">Войти</button></form></div>

  return <div className="adminShell">
    <aside className="adminSide"><div className="adminBrand"><span className="mark small">W</span><div><b>Admin</b><span>WorkKit v3</span></div></div><nav><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><BarChart3/>Обзор</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}><ClipboardList/>Заказы</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}><Box/>Предложения</button><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings2/>Вид сайта</button></nav><button className="adminLogout" onClick={logout}><LogOut/>Выйти</button></aside>
    <section className="adminMain"><div className="adminTop"><div><span className="eyebrow">ПАНЕЛЬ УПРАВЛЕНИЯ</span><h1>{tab==='overview'?'Обзор':tab==='orders'?'Заказы':tab==='products'?'Предложения':'Настройки сайта'}</h1></div><button className="secondary" onClick={load}><RefreshCw size={16}/> Обновить</button></div>{error&&<div className="formError">{error}</div>}

      {tab==='overview'&&summary&&<><div className="adminStats"><div><span>Всего заказов</span><b>{summary.orders_total}</b><ClipboardList/></div><div><span>Открытые</span><b>{summary.orders_open}</b><UsersRound/></div><div><span>Оплачено</span><b>{money(summary.revenue_paid)}</b><BarChart3/></div><div><span>Активных предложений</span><b>{summary.products_active}/{summary.products_total}</b><Box/></div></div><div className="adminPanel"><div className="adminPanelHead"><div><h2>Последние заказы</h2><p>Быстрый контроль текущей работы</p></div><button onClick={()=>setTab('orders')}>Все заказы →</button></div><OrderTable orders={orders.slice(0,6)} onStatus={changeStatus}/></div></>}

      {tab==='orders'&&<div className="adminPanel"><div className="adminToolbar"><div className="adminSearch"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Номер, e-mail, клиент или услуга"/></div><span>{filtered.length} заказов</span></div><OrderTable orders={filtered} onStatus={changeStatus}/></div>}

      {tab==='products'&&<div className="adminPanel"><div className="adminPanelHead"><div><h2>Предложения и цены</h2><p>Карточки, видимость, цены и тип исполнения. Это базовая CMS для быстрой смены ассортимента.</p></div><button className="primary" onClick={()=>setAdding(v=>!v)}><Plus size={16}/> Добавить</button></div>{adding&&<NewProductForm onCreate={createProduct}/>}<div className="adminProducts">{products.map(p=><ProductEditor key={p.id} product={p} onToggle={()=>toggleProduct(p)} onVariant={updateVariant} onSaved={load}/>)}</div></div>}

      {tab==='settings'&&config&&<form className="adminPanel settingsForm" onSubmit={saveConfig}><div className="adminPanelHead"><div><h2>Конфигурируемая оболочка</h2><p>Эти значения хранятся в БД. Большую часть позиционирования можно менять без правки React.</p></div><button className="primary" disabled={busy}><Save size={16}/>{busy?'Сохраняю…':'Сохранить'}</button></div><div className="presetRow"><b>Быстрый формат:</b><button type="button" onClick={()=>applyPreset('services')}>Услуги</button><button type="button" onClick={()=>applyPreset('digital')}>Цифровые товары</button><button type="button" onClick={()=>applyPreset('subscription')}>Подписка</button></div><div className="settingsGrid"><Field label="Название бренда" value={config.brand_name} onChange={v=>patchConfig('brand_name',v)}/><Field label="Короткое название" value={config.brand_short} onChange={v=>patchConfig('brand_short',v)}/><Field label="Знак" value={config.brand_mark} onChange={v=>patchConfig('brand_mark',v)}/><Field label="Акцентный цвет" type="color" value={config.accent_color} onChange={v=>patchConfig('accent_color',v)}/><Field wide label="Подзаголовок бренда" value={config.tagline} onChange={v=>patchConfig('tagline',v)}/><Field label="Подпись каталога" value={config.catalog_label} onChange={v=>patchConfig('catalog_label',v)}/><Field label="Как называть единицу" value={config.item_label} onChange={v=>patchConfig('item_label',v)}/><Field label="Главная кнопка заказа" value={config.order_cta} onChange={v=>patchConfig('order_cta',v)}/><Field label="Eyebrow первого экрана" value={config.hero_eyebrow} onChange={v=>patchConfig('hero_eyebrow',v)}/><Field label="CTA первого экрана" value={config.hero_cta} onChange={v=>patchConfig('hero_cta',v)}/><Field wide label="Заголовок первого экрана" value={config.hero_title} onChange={v=>patchConfig('hero_title',v)}/><Field wide textarea label="Описание первого экрана" value={config.hero_text} onChange={v=>patchConfig('hero_text',v)}/><Field label="Промо-заголовок" value={config.promo_title} onChange={v=>patchConfig('promo_title',v)}/><Field label="Режим работы" value={config.work_hours} onChange={v=>patchConfig('work_hours',v)}/><Field wide label="Промо-текст" value={config.promo_text} onChange={v=>patchConfig('promo_text',v)}/></div><h3 className="settingsSection">Контакты и реквизиты</h3><div className="settingsGrid"><Field label="E-mail" value={config.support_email} onChange={v=>patchConfig('support_email',v)}/><Field label="Телефон" value={config.support_phone} onChange={v=>patchConfig('support_phone',v)}/><Field wide label="Исполнитель / компания" value={config.seller_name} onChange={v=>patchConfig('seller_name',v)}/><Field label="ИНН" value={config.seller_inn} onChange={v=>patchConfig('seller_inn',v)}/><Field label="ОГРН / ОГРНИП" value={config.seller_ogrn} onChange={v=>patchConfig('seller_ogrn',v)}/><Field wide label="Адрес" value={config.seller_address} onChange={v=>patchConfig('seller_address',v)}/></div></form>}
    </section>
  </div>
}

function OrderTable({orders,onStatus}:{orders:Order[];onStatus:(id:string,status:string)=>void}){return <div className="adminTableWrap"><table className="adminTable"><thead><tr><th>Заказ</th><th>Клиент</th><th>Предложение</th><th>Сумма</th><th>Дата</th><th>Статус</th></tr></thead><tbody>{orders.map(o=><tr key={o.public_id}><td><b>#{o.public_id}</b></td><td><b>{o.customer_name||'Клиент'}</b><span>{o.customer_email}</span></td><td>{o.items[0]?.title}<span>{o.items[0]?.variant}</span></td><td><b>{money(o.total_amount)}</b></td><td>{new Date(o.created_at).toLocaleDateString('ru-RU')}</td><td><select className={`adminStatus ${o.status}`} value={o.status} onChange={e=>onStatus(o.public_id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select></td></tr>)}</tbody></table>{orders.length===0&&<div className="empty">Заказов пока нет</div>}</div>}

function ProductEditor({product,onToggle,onVariant,onSaved}:{product:Product;onToggle:()=>void;onVariant:(id:number,price:string,old:string,type:string)=>void;onSaved:()=>Promise<void>}){const[edit,setEdit]=useState(false);const[title,setTitle]=useState(product.title);const[short,setShort]=useState(product.short_description);const[description,setDescription]=useState(product.description);const[image,setImage]=useState(product.image_url);async function save(){await api.admin.updateProduct(product.id,{title,short_description:short,description,image_url:image});setEdit(false);await onSaved()}return <div className={`adminProduct ${!product.active?'inactive':''}`}><img src={product.image_url}/><div className="adminProductInfo"><span>{product.category_name}</span><h3>{product.title}</h3><p>{product.short_description}</p><div className="adminVariants">{product.variants.map(v=><VariantEditor key={v.id} variant={v} onSave={onVariant}/>)}</div><button className="textButton" onClick={()=>setEdit(v=>!v)}>{edit?'Закрыть':'Редактировать карточку'}</button>{edit&&<div className="productEditGrid"><label>Название<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Короткое описание<input value={short} onChange={e=>setShort(e.target.value)}/></label><label className="wide">Изображение URL<input value={image} onChange={e=>setImage(e.target.value)}/></label><label className="wide">Описание<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primary" onClick={save}><Save size={15}/> Сохранить карточку</button></div>}</div><label className="switchRow"><input type="checkbox" checked={product.active} onChange={onToggle}/><span>{product.active?'На сайте':'Скрыто'}</span></label></div>}

function NewProductForm({onCreate}:{onCreate:(p:{title:string;slug:string;category:string;price:string;image_url:string;short_description:string})=>Promise<void>}){const[title,setTitle]=useState('');const[slug,setSlug]=useState('');const[category,setCategory]=useState('Другое');const[price,setPrice]=useState('990.00');const[image,setImage]=useState('https://images.unsplash.com/photo-1497215842964-222b430dc094?auto=format&fit=crop&w=1200&q=80');const[short,setShort]=useState('Краткое описание нового предложения.');return <div className="newProductForm"><label>Название<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Slug<input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="new-offer"/></label><label>Категория<input value={category} onChange={e=>setCategory(e.target.value)}/></label><label>Цена<input value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="wide">Изображение URL<input value={image} onChange={e=>setImage(e.target.value)}/></label><label className="wide">Описание<input value={short} onChange={e=>setShort(e.target.value)}/></label><button className="primary" disabled={!title||!slug||!price} onClick={()=>onCreate({title,slug,category,price,image_url:image,short_description:short})}><Plus size={15}/> Создать предложение</button></div>}

function VariantEditor({variant,onSave}:{variant:Product['variants'][number];onSave:(id:number,price:string,old:string,type:string)=>void}){const[price,setPrice]=useState(variant.price);const[old,setOld]=useState(variant.old_price||'');const[type,setType]=useState(variant.delivery_type);return <div className="variantEditor"><b>{variant.name}</b><label>Цена<input value={price} onChange={e=>setPrice(e.target.value)}/></label><label>Старая<input value={old} onChange={e=>setOld(e.target.value)} placeholder="—"/></label><label>Тип<select value={type} onChange={e=>setType(e.target.value)}><option value="service">Услуга</option><option value="download">Файл</option><option value="access">Доступ</option><option value="subscription">Подписка</option></select></label><button onClick={()=>onSave(variant.id,price,old,type)} title="Сохранить"><Check/></button></div>}

function Field({label,value,onChange,wide,textarea,type='text'}:{label:string;value:string;onChange:(v:string)=>void;wide?:boolean;textarea?:boolean;type?:string}){return <label className={wide?'wide':''}><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
