import {FormEvent,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {api,session} from '../api'
import {LockKeyhole,ShieldCheck,UserPlus} from 'lucide-react'

export default function Login(){
  const nav=useNavigate();const[mode,setMode]=useState<'login'|'register'>('login');const[error,setError]=useState('');const[busy,setBusy]=useState(false)
  const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[phone,setPhone]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setError('');setBusy(true);try{const data=mode==='login'?await api.login(email,password):await api.register({full_name:name,email,password,phone:phone||undefined});session.save(data);nav('/account')}catch(err){setError(err instanceof Error?err.message:'Не удалось выполнить запрос')}finally{setBusy(false)}}
  return <div className="container page authWrap"><section className="authIntro"><span className="eyebrow">ЛИЧНЫЙ КАБИНЕТ</span><h1>Все заказы и статусы в одном месте</h1><p>Создайте аккаунт один раз. В кабинете будут храниться заявки, суммы, текущий статус и результат выполненной услуги.</p><div className="authBenefits"><div><ShieldCheck/>Пароль хранится только в виде защищённого хэша</div><div><LockKeyhole/>Заказы видит только авторизованный пользователь</div></div></section><form className="authCard" onSubmit={submit}><div className="authTabs"><button type="button" className={mode==='login'?'active':''} onClick={()=>setMode('login')}>Вход</button><button type="button" className={mode==='register'?'active':''} onClick={()=>setMode('register')}>Регистрация</button></div><h2>{mode==='login'?'С возвращением':'Создать аккаунт'}</h2><p>{mode==='login'?'Введите данные, указанные при регистрации.':'Регистрация займёт меньше минуты.'}</p>{mode==='register'&&<><label>Имя и фамилия<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} placeholder="Иван Петров"/></label><label>Телефон <span className="muted">(необязательно)</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+7 900 000-00-00"/></label></>}<label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="client@example.ru"/></label><label>Пароль<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Не менее 8 символов"/></label>{error&&<div className="formError">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Подождите…':mode==='login'?'Войти':'Зарегистрироваться'}</button><small>Продолжая, вы соглашаетесь с <Link to="/offer">офертой</Link> и <Link to="/privacy">политикой конфиденциальности</Link>.</small>{mode==='register'&&<div className="authNote"><UserPlus size={18}/>После регистрации можно сразу оформить первую заявку.</div>}</form></div>
}
